### ISSUE TITLE
Split code and more ideas

### ISSUE THREAD

**Issue by frite** [rackerlabs/scantron#130]
Hi all, more of an umbrella issue to keep spam low.
Anyway, I'd like to propose the following:

- Although the codebase is not exactly huge, I think it can be split in separate repos. i.e. Ansible roles can go each in a repository. This will enable to develop tests. I'm happy to use molecule tests (at least for the happy paths) to ensure that roles work as expected, potentially it also helps to onboard people faster (because if tests break you broke something). Also, that way they can be pushed into Ansible Galaxy. Finally, it makes the playbooks smaller because you can `rackspace.scantron_common_role` in your playbook. 
- Same as above for agent/master. Again the same reasoning.
- More of a thought at this stage but. Agents can be containerized and come up on demand (Happy to containerize the agent as well). If multi-agent support is developed, it may be worth it to even have some option of Kubernetes cluster. Realistically speaking, even if you scan your fleet daily, there's a big part of that day that your fleet is idle. Similar approach can be taken for master although I currently can't think of any use, unless web/db is split. 

Regards, 
Manolis

**Comment by derpadoo** [comment]
Hi @frite - thanks for taking the time to provide some ideas!

* I definitely like the idea of automated testing for the Ansible playbooks, but favor the mono repo for now because I'd estimate most Scantron users (likely infosec folks) aren't well versed in Ansible, Ansible Galaxy (myself included), or molecule testing (had to look that one up) already.  I'll have to read up more on that, but for now, it's easier keeping it in one repo.

* Would definitely be interested in a containerized solution, for at least the agents, if you were willing to provide the code.  Admittedly, there's so much to learn and I've been slow to jump on the the container train.

**Comment by derpadoo** [comment]
Hi @frite - A Scantron engine docker container ticket can be found here that I could use another set of eyes to validate if you're still interested in this project: https://github.com/rackerlabs/scantron/issues/78

Going to close this one out for now.
