### ISSUE TITLE
Error on engine while executing task

### ISSUE THREAD

**Issue by albertcp** [rackerlabs/scantron#265]
Hi everyone!

I have a problem with the target scanning on the engine.

I've set up scantron on virtual machines. One VM for the console and other VM for the engine. It's all working, ssh tunnels are created, crontabs are executing correctly...

The thing is when I create a new scan. It can be created and the status is pending:

<img width="677" alt="Captura" src="https://user-images.githubusercontent.com/6135669/118259825-e8a0de80-b4b1-11eb-8f64-fa6428a1922b.PNG">

Then, the status changes to error. When I see the engine log, this is what is showing:

<img width="471" alt="Captura" src="https://user-images.githubusercontent.com/6135669/118260074-2e5da700-b4b2-11eb-9f81-808ef4351417.PNG">

I checked the code of engine.py and there is some problem with the field "config_data"... I don't know what can be the error.

If someone can help me I will be very gratefull.

**Comment by derpadoo** [comment]
Hi @albertcp - sorry to hear it's not working.  To doublecheck:

1) What version of the agent are you running? `./engine -v`

2) How are you executing it?
- Binary: `./engine`
- Python script `/root/engine/.venv/bin/python engine.py`
- Service? `systemctl start scantron-engine`

3) Does the `engine_config.json` file exist in the `/root/engine` directory of the engine?  If so, can you provide a redacted screenshot of your `engine_config.json` file?

4) Have the `scan_engine` and `api_token` values been updated to reflect a valid user and API token?  If you used Ansible to deploy the console, a `engine1` user (https://CONSOLE_IP/scantron-admin/auth/user/) should have been created along with an API key (https://CONSOLE_IP/scantron-admin/authtoken/tokenproxy/)

5) Is the engine running as root?

**Comment by albertcp** [comment]
Hi @derpadoo, I have checked everything you asked me. Below, you can find the results:

1. _What version of the agent are you running?_

**Answer**:  1.03

2. _How are you executing it?_

**Answer**: I activated the service ```systemctl start scantron-engine```. But, checking the service ("```cat scantron-engine.service```") the output is:

![image](https://user-images.githubusercontent.com/6135669/118450826-e4b0ce80-b6f4-11eb-8185-fbf3d8879300.png)


So I suppose the way it executes is using the python script: ```/root/engine/.venv/bin/python engine.py```

3. _Does the engine_config.json file exist in the /root/engine directory of the engine? If so, can you provide a redacted screenshot of your engine_config.json file?_

**Answer**: Yes, ```engine_config.json``` exists.

![image](https://user-images.githubusercontent.com/6135669/118451757-dd3df500-b6f5-11eb-8afb-d7710802108f.png)

4. _Have the scan_engine and api_token values been updated to reflect a valid user and API token? If you used Ansible to deploy the console, a engine1 user (https://CONSOLE_IP/scantron-admin/auth/user/) should have been created along with an API key (https://CONSOLE_IP/scantron-admin/authtoken/tokenproxy/)_

**Answer:** I access that URL and checked the info is correct.

![image](https://user-images.githubusercontent.com/6135669/118453320-5db12580-b6f7-11eb-8edf-4e2732dbb3bf.png)

5. _Is the engine running as root?_

**Answer:** Engine files are in ```/root/``` folder. So, I need root to execute the engine.


I hope all questions are answered  as expected.

Best regards.

**Comment by derpadoo** [comment]
Appreciate you taking the time to provide that info.

When you ran the Ansible playbook, what did you have this value set to?

https://github.com/rackerlabs/scantron/blob/ee8e22ecc65b3cce592df6146bacefcdceb60341/ansible-playbooks/group_vars/all#L25

An explanation of that setting can be found in this [section](https://github.com/rackerlabs/scantron/blob/master/README.md#console-installation)

From your original screenshots, it looks like the engine authenticates properly, but just to be sure, let's try the following.  It looks like the "scan_engine" value in `engine_config.json` is set to `engine-510598`, but needs to match the user `engine1`.  You have two options:

1) Create a `engine-510598` user, which will generate a new API key that you need to update in `engine_config.json`
2) Update the "scan_engine" value in `engine_config.json` to be `engine1`.

Since you're using the service, you can run `systemctl start scantron-engine` to start the engine service or `systemctl start scantron-engine` to stop it.

**Comment by albertcp** [comment]
First of all, thank you for your quick respone.

1. Ansible playbook config value is set to:
```
utilize_static_api_token_across_engines: True
```

Do I need to set the value to False?

2. I created a new user called ```engine-510598``` & updated the API key in the ```engine_config.json``` and the same error:

![image](https://user-images.githubusercontent.com/6135669/118613325-efd03100-b7be-11eb-9793-da39d6f07d98.png)

The image is taken from the engine.log

**Comment by derpadoo** [comment]
Ahh, I see it.  The `engine_config.json` files needs a "supported_scan_binaries" key.  See https://github.com/rackerlabs/scantron/blob/master/engine/engine_config.json#L12

I updated the `engine_config.json` a while back without updating the file below, since I don't use the `utilize_static_api_token_across_engines` in my prod environment.

I need to update https://github.com/rackerlabs/scantron/blob/master/ansible-playbooks/roles/engine/templates/engine_config.json

For your fix, add the highlighted portion below:

![image](https://user-images.githubusercontent.com/27816854/118713020-1904b780-b7e7-11eb-8022-70fc7070bff9.png)

```python
    "http_useragent": "user-agent",
    "supported_scan_binaries": [
        "nmap",
        "masscan"
    ]
```

**Comment by derpadoo** [comment]
Merged in https://github.com/rackerlabs/scantron/pull/266

**Comment by derpadoo** [comment]
@albertcp I'll wait to ensure it works for you before closing this one out.

**Comment by albertcp** [comment]
@derpadoo Thank you so much for everything!!! It Works!!!!
