### ISSUE TITLE
Lessons learned getting scantron to work.

### ISSUE THREAD

**Issue by 0xtavian** [rackerlabs/scantron#31]
Do Not attempt to deploy agents from a node you plan to deploy your master on!
Always deploy the first agent before the master.

Create a local ubuntu VM and generate SSH keys via ssh-keygen. Add the public key to your agents and Master authorized_keys file /.ssh/authorized_keys 

You’ll need python3-pip installed on (all?) boxes and this is never mentioned

if you install ansible with pip as a user instead of root, you’ll have to add ansible to path

`export PATH="$PATH:/home/{username}/.local/bin/"`
logout of session completely

you probably want to install net-tools as well
apt-get install net-tools

for this ansible workload to work on IBM Cloud: edit the File "/boot/grub/menu.lst" by changing
`# groot=LABEL... `
to
`# groot=(hd0)`
then run
` sudo update-grub-legacy-ec2` 

reference https://developer.ibm.com/answers/questions/462237/error-groot-must-be-grub-root-device-on-ubuntu/

When editing scantron_secrets.json you might not be able to log into the web app if you use different passwords and/or lengths longer than 13 (idk why but this happened to me). The default username is admin

Important there CANNOT be a space between –private-key={location of ssh key} and use -vvv to increase verbosity during first time install to check for any errors. Examples below:

`ansible-playbook agent.yml -u ubuntu --become --private-key=../.ssh/id_rsa -vvv`

OR

`ansible-playbook agent.yml -u root --private-key=../.ssh/id_rsa -vvv`

The docs suggest you wont have to add the first agents API key to /root/agent_config but you will!

**Comment by derpadoo** [comment]
Thanks for the awesome notes!  Some have already been merged into master from https://github.com/rackerlabs/scantron/pull/37 Please see my responses in bold below.

====

Do Not attempt to deploy agents from a node you plan to deploy your master on!  **(I haven't tried this yet, what was your experience, issues you encountered?)**

Always deploy the first agent before the master. **(already noted in README, "The recommendation is to deploy the agents first.", https://github.com/rackerlabs/scantron/blob/master/README.md#update-agent-ansible-variables,** 

Create a local ubuntu VM and generate SSH keys via ssh-keygen. Add the public key to your agents and Master authorized_keys file /.ssh/authorized_keys **(initial_setup.sh should take care of this, see script below)**:

```bash
#!/bin/bash

# Install Ansible with pip.
echo "[*] Install ansible >=2.4.0.0 using pip"
pip3 install ansible\>=2.4.0.0

# Generate a passphrase-less SSH key pair for the autossh user.
echo "[*] Generating a passphrase-less SSH key pair for the autossh user"
ssh-keygen -b 4096 -t rsa -f autossh -q -N ""

# Move public key to the respective location for Ansible.
echo "[*] Move public SSH key to the Agent's ansible role."
mv autossh.pub ansible-playbooks/roles/agent/files/autossh.pub

# Move and rename private key to the respective location for Ansible.
echo "[*] Move private SSH key to the Master's ansible role."
mv autossh master/autossh.key

# Create empty scantron_secrets.json from scantron_secrets.json.empty.
cp master/scantron_secrets.json.empty master/scantron_secrets.json
```

You’ll need python3-pip installed on (all?) boxes and this is never mentioned **(Added line noting that for the host box: `apt install python3-pip -y`) and also to the initial_setup.sh script.  python3-pip is installed on Master and agents through Ansible (https://github.com/rackerlabs/scantron/blob/master/ansible-playbooks/roles/master/vars/main.yml#L11 and https://github.com/rackerlabs/scantron/blob/master/ansible-playbooks/roles/agent/vars/main.yml#L10)**

if you install ansible with pip as a user instead of root, you’ll have to add ansible to path

export PATH="$PATH:/home/{username}/.local/bin/"
logout of session completely

you probably want to install net-tools as well
apt-get install net-tools **(on host, Master, agent, or all?)**

for this ansible workload to work on IBM Cloud: edit the File "/boot/grub/menu.lst" by changing

```
# groot=LABEL...
to
# groot=(hd0)
```
**(Added Cloud Provider Caveats section with this)**

When editing scantron_secrets.json you might not be able to log into the web app if you use different passwords and/or lengths longer than 13 (idk why but this happened to me). The default username is admin **(Can you expand on this one some more?  The minimum password length is https://github.com/rackerlabs/scantron/blob/master/master/config/settings/base.py#L225)**

Important there CANNOT be a space between –private-key={location of ssh key} and use -vvv to increase verbosity during first time install to check for any errors. Examples below:

ansible-playbook agent.yml -u ubuntu --become --private-key=../.ssh/id_rsa -vvv

OR

ansible-playbook agent.yml -u root --private-key=../.ssh/id_rsa -vvv
**(Was this an oversight on your end, or did you copy paste something from the README that had it?  I can't find a discrepancy in the README.)**

The docs suggest you wont have to add the first agents API key to /root/agent_config but you will! **(Was this prior to running the Ansible playbook?  The README notes that 'The "api_token" will have to be modified on all the agents after deploying master!'**

**Comment by 0xtavian** [comment]
thanks for the detailed reply! we will tackle these issues individually in other issues!
