### ISSUE TITLE
Bad Request returned for all web access

### ISSUE THREAD

**Issue by F13** [rackerlabs/scantron#66]
Hi, I'm trying to set up scantron and am having issues. I believe everything installed correctly and the master and agent are talking to each other. However, when I attempt to connect to the master's IP address, no matter what URL I use, I am greeted with a Bad Request (400) response.

Where might I go looking for log files to diagnose the issue here?

Thanks!

**Comment by derpadoo** [comment]
Hi @F13 - an HTTP 400 is usually because the IPs/domains in Django's `ALLOWED_HOSTS` are not correct.  Check `/home/scantron/master/config/settings/production.py` file and ensure the IP and/or domain being used are populated correctly.  They should be populated automatically by Ansible, but that may break if you customized some stuff.

![capture](https://user-images.githubusercontent.com/27816854/50782518-da04e580-126d-11e9-96d8-94d0f3e2bb75.PNG)

To answer your question though, the README.md should help you out: https://github.com/rackerlabs/scantron#master-troubleshooting

**Comment by derpadoo** [comment]
Then restart uwsgi...`systemctl restart uwsgi`

**Comment by F13** [comment]
Thanks, that got me through. I am setting this up under Google Cloud and had to add the public IP of the host (which the host is generally unaware of) in order to connect. It might be worth mentioning this caveat somewhere in the setup instructions.

Thanks for the help!

**Comment by derpadoo** [comment]
Thanks for the tip...I haven't deployed on GCP yet.  Added issue https://github.com/rackerlabs/scantron/issues/67
